### ISSUE TITLE
使用手册md 链接404找不到了

### ISSUE THREAD

**Issue by lvye351** [actiontech/dble-test-suite#158]
* **Description ：**  
使用手册 
https://github.com/actiontech/dble-test-suite/blob/master/docs/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md  404 
* **Steps to reproduce the issue:**   

* **Describe the results you received：**  
    1.
* **Describe the results you expected：**  
    1.
* **dble-test-suite version：** 
    
* **Additional information you deem important (e.g. issue happens only occasionally)：**  
    1.
* **Additional details (log, config, job config etc):**

**Comment by jndxcaiwei** [comment]
fixed on: db546160ff2765d7995dce466060f041be1c85ca
